name: file_picker_cross
description: Select, open, choose or pick documents, images videos or other files on Android, iOS, the desktop and the web for reading, writing, use as String, byte list or HTTP uploads.
version: 4.5.0
homepage: https://gitlab.com/testapp-system/file_picker_cross
repository: https://gitlab.com/testapp-system/file_picker_cross.git
issue_tracker: https://gitlab.com/testapp-system/file_picker_cross/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^4.1.3
  http: ^0.13.3
  http_parser: ^4.0.0
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  path_provider: ^2.0.2
  package_info: ^2.0.1
  share: ^2.0.2
  disk_space: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0
